In [1]:
import pandas as pd
import numpy as np

In [84]:
bank_train_data = r'C:\Users\narma\Dropbox\datasets_edvancer_project\bank_problem\bank-full_train.csv'
bank_train = pd.read_csv(bank_train_data)

prediction_data = r'C:\Users\narma\Dropbox\datasets_edvancer_project\bank_problem\bank-full_test.csv'
predict_df = pd.read_csv(prediction_data)

In [87]:
predict_df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,ID
0,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,3
1,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,4
2,35,management,married,tertiary,no,231,yes,no,unknown,5,may,139,1,-1,0,unknown,6
3,28,management,single,tertiary,no,447,yes,yes,unknown,5,may,217,1,-1,0,unknown,7
4,58,technician,married,unknown,no,71,yes,no,unknown,5,may,71,1,-1,0,unknown,14

In [14]:
bank_train.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,ID,y
0,45,blue-collar,married,secondary,no,2,no,no,cellular,26,aug,105,10,-1,0,unknown,22944,no
1,34,admin.,divorced,secondary,no,0,no,no,cellular,10,jul,268,1,-1,0,unknown,13870,no
2,40,technician,divorced,secondary,no,311,no,no,cellular,6,aug,738,2,-1,0,unknown,19301,yes
3,58,self-employed,married,tertiary,no,5810,no,no,cellular,12,mar,139,1,-1,0,unknown,31334,yes
4,59,blue-collar,married,secondary,no,169,yes,no,unknown,16,may,181,3,-1,0,unknown,3849,no

In [6]:
bank_train.isna().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
ID           0
y            0
dtype: int64

In [10]:
bank_train.duplicated().value_counts()

False    31647
Name: count, dtype: int64

In [15]:
bank_train.nunique()

age             75
job             12
marital          3
education        4
default          2
balance       6245
housing          2
loan             2
contact          3
day             31
month           12
duration      1454
campaign        46
pdays          511
previous        38
poutcome         4
ID           31647
y                2
dtype: int64

In [19]:
num_cols = bank_train[['age','balance','day','duration','campaign','pdays','previous','ID','y']]

In [33]:
bank_train_copy = bank_train

In [38]:
binary_col = ['age','default','housing','loan','y']

In [40]:
bank_train_copy[binary_col] = bank_train_copy[binary_col].replace ( { 'no':0 , 'yes': 1})
bank_train_copy

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,ID,y
0,45,blue-collar,married,secondary,0,2,0,0,cellular,26,aug,105,10,-1,0,unknown,22944,0
1,34,admin.,divorced,secondary,0,0,0,0,cellular,10,jul,268,1,-1,0,unknown,13870,0
2,40,technician,divorced,secondary,0,311,0,0,cellular,6,aug,738,2,-1,0,unknown,19301,1
3,58,self-employed,married,tertiary,0,5810,0,0,cellular,12,mar,139,1,-1,0,unknown,31334,1
4,59,blue-collar,married,secondary,0,169,1,0,unknown,16,may,181,3,-1,0,unknown,3849,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31642,37,technician,married,secondary,0,6963,1,0,cellular,22,dec,158,2,-1,0,unknown,42547,0
31643,54,management,married,tertiary,0,8295,0,0,cellular,2,oct,849,2,119,1,success,41684,1
31644,47,technician,married,tertiary,0,192,1,0,unknown,26,may,596,1,-1,0,unknown,5827,0
31645,39,admin.,married,secondary,0,0,1,0,cellular,17,jul,69,1,-1,0,unknown,15012,0
31646,46,blue-collar,married,primary,0,143,1,0,unknown,7,may,279,1,-1,0,unknown,965,0

In [41]:
num_cols = bank_train_copy[['age','balance','day','duration','campaign','pdays','previous','ID','y']]
num_cols.corr()

,age,balance,day,duration,campaign,pdays,previous,ID,y
age,1.000000,0.104712,-0.006600,-0.007348,0.001913,-0.020160,0.004687,0.015275,0.028749
balance,0.104712,1.000000,0.007062,0.016683,-0.016555,0.003595,0.014816,0.074520,0.055769
day,-0.006600,0.007062,1.000000,-0.032348,0.164046,-0.094333,-0.051682,-0.059522,-0.025457
duration,-0.007348,0.016683,-0.032348,1.000000,-0.084246,-0.002576,-0.000881,0.010979,0.393125
campaign,0.001913,-0.016555,0.164046,-0.084246,1.000000,-0.088245,-0.028829,-0.105699,-0.076647
pdays,-0.020160,0.003595,-0.094333,-0.002576,-0.088245,1.000000,0.428668,0.437037,0.103892
previous,0.004687,0.014816,-0.051682,-0.000881,-0.028829,0.428668,1.000000,0.255305,0.087088
ID,0.015275,0.074520,-0.059522,0.010979,-0.105699,0.437037,0.255305,1.000000,0.294758
y,0.028749,0.055769,-0.025457,0.393125,-0.076647,0.103892,0.087088,0.294758,1.000000

In [42]:
bank_train_copy = bank_train_copy.drop('ID',axis = 1)
bank_train_copy

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,45,blue-collar,married,secondary,0,2,0,0,cellular,26,aug,105,10,-1,0,unknown,0
1,34,admin.,divorced,secondary,0,0,0,0,cellular,10,jul,268,1,-1,0,unknown,0
2,40,technician,divorced,secondary,0,311,0,0,cellular,6,aug,738,2,-1,0,unknown,1
3,58,self-employed,married,tertiary,0,5810,0,0,cellular,12,mar,139,1,-1,0,unknown,1
4,59,blue-collar,married,secondary,0,169,1,0,unknown,16,may,181,3,-1,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31642,37,technician,married,secondary,0,6963,1,0,cellular,22,dec,158,2,-1,0,unknown,0
31643,54,management,married,tertiary,0,8295,0,0,cellular,2,oct,849,2,119,1,success,1
31644,47,technician,married,tertiary,0,192,1,0,unknown,26,may,596,1,-1,0,unknown,0
31645,39,admin.,married,secondary,0,0,1,0,cellular,17,jul,69,1,-1,0,unknown,0
31646,46,blue-collar,married,primary,0,143,1,0,unknown,7,may,279,1,-1,0,unknown,0

In [49]:
bank_train_copy = pd.get_dummies(bank_train_copy)

In [50]:
bank_train_copy

,age,default,balance,housing,loan,day,duration,campaign,pdays,previous,...,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,45,0,2,0,0,26,105,10,-1,0,...,False,False,False,False,False,False,False,False,False,True
1,34,0,0,0,0,10,268,1,-1,0,...,False,False,False,False,False,False,False,False,False,True
2,40,0,311,0,0,6,738,2,-1,0,...,False,False,False,False,False,False,False,False,False,True
3,58,0,5810,0,0,12,139,1,-1,0,...,False,True,False,False,False,False,False,False,False,True
4,59,0,169,1,0,16,181,3,-1,0,...,False,False,True,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31642,37,0,6963,1,0,22,158,2,-1,0,...,False,False,False,False,False,False,False,False,False,True
31643,54,0,8295,0,0,2,849,2,119,1,...,False,False,False,False,True,False,False,False,True,False
31644,47,0,192,1,0,26,596,1,-1,0,...,False,False,True,False,False,False,False,False,False,True
31645,39,0,0,1,0,17,69,1,-1,0,...,False,False,False,False,False,False,False,False,False,True
31646,46,0,143,1,0,7,279,1,-1,0,...,False,False,True,False,False,False,False,False,False,True

In [51]:
y = bank_train['y']

In [56]:
x = bank_train_copy.drop('y',axis = 1)

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
x_train , x_test , y_train ,y_test = train_test_split ( x, y, test_size =0.3 , stratify = y, random_state = 17 ) 
## include stratify = y

In [60]:
x_train.shape

(22152, 48)

In [62]:
y_test.shape

(9495,)

In [67]:
from sklearn.ensemble import RandomForestClassifier

In [68]:
from sklearn.model_selection import RandomizedSearchCV , GridSearchCV

In [69]:
clf = RandomForestClassifier()

In [70]:
param_dist = {'class_weight':['balanced'], 
        'criterion':['entropy','gini','log_loss'], ## added log_loss
        'max_depth':[None,5,10,15,20,30,50,70],
        'min_samples_split':[20,25,30,35,40,45,50,55,70],
        'min_samples_leaf':[5,10,15,20,25,30,35,40,], # Till here, its same as DT
              
        "n_estimators":[100,200,300,500], # Number of trees to build
        "max_features": [6,7,9,12,15,17],
          "max_samples": [None, 0.7, 0.8]
         }

In [71]:
random_search = RandomizedSearchCV(clf, param_distributions=param_dist,
                                   n_iter=20,
                                   scoring='roc_auc',
                                   cv=5,
                                   n_jobs=-1, 
                                   verbose=20, 
                                   random_state = 7).fit(x_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

In [72]:
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        # np.flatnonzero(): Return the indices of the non-zero elements
        
        for candidate in candidates:
            print(f"Model with rank: {i}")
            print(f"Mean validation score: {round(results['mean_test_score'][candidate], 5)} \
                  std: {round(results['std_test_score'][candidate], 5)}")
            print(f"Parameters: {results['params'][candidate]}")
            print("")

In [73]:
random_search.best_estimator_

RandomForestClassifier(class_weight='balanced', criterion='log_loss',
                       max_depth=70, max_features=7, max_samples=0.8,
                       min_samples_leaf=5, min_samples_split=55,
                       n_estimators=500)

In [74]:
report(random_search.cv_results_,3)

Model with rank: 1
Mean validation score: 0.92586                   std: 0.00483
Parameters: {'n_estimators': 500, 'min_samples_split': 55, 'min_samples_leaf': 5, 'max_samples': 0.8, 'max_features': 7, 'max_depth': 70, 'criterion': 'log_loss', 'class_weight': 'balanced'}

Model with rank: 2
Mean validation score: 0.92576                   std: 0.00652
Parameters: {'n_estimators': 500, 'min_samples_split': 20, 'min_samples_leaf': 10, 'max_samples': 0.8, 'max_features': 15, 'max_depth': 15, 'criterion': 'entropy', 'class_weight': 'balanced'}

Model with rank: 3
Mean validation score: 0.9247                   std: 0.00459
Parameters: {'n_estimators': 500, 'min_samples_split': 70, 'min_samples_leaf': 5, 'max_samples': 0.7, 'max_features': 6, 'max_depth': 20, 'criterion': 'log_loss', 'class_weight': 'balanced'}

In [75]:
rf = RandomForestClassifier(** {'n_estimators': 500, 'min_samples_split': 55, 'min_samples_leaf': 5, 'max_samples': 0.8, 'max_features': 7, 'max_depth': 70, 'criterion': 'log_loss', 'class_weight': 'balanced' } ).fit(x_train, y_train)

In [79]:
from sklearn.metrics import roc_auc_score ,precision_score, recall_score, accuracy_score, f1_score ,roc_curve

In [78]:
y_pred_proba = rf.predict_proba(x_test)[:,1]
auc_score = roc_auc_score(y_test , y_pred_proba)
auc_score

0.9233417003851154

In [81]:
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)

In [82]:
# Compute the KS score
ks_score = max(tpr - fpr)
print(f"KS Score: {ks_score}")

KS Score: 0.714322288055007

In [89]:
binary_col_p = ['age','default','housing','loan']

In [90]:
predict_df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,ID
0,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,3
1,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,4
2,35,management,married,tertiary,no,231,yes,no,unknown,5,may,139,1,-1,0,unknown,6
3,28,management,single,tertiary,no,447,yes,yes,unknown,5,may,217,1,-1,0,unknown,7
4,58,technician,married,unknown,no,71,yes,no,unknown,5,may,71,1,-1,0,unknown,14

In [92]:
predict_df[binary_col_p] = predict_df[binary_col_p].replace ( { 'no':0 , 'yes': 1})
predict_df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,ID
0,33,entrepreneur,married,secondary,0,2,1,1,unknown,5,may,76,1,-1,0,unknown,3
1,47,blue-collar,married,unknown,0,1506,1,0,unknown,5,may,92,1,-1,0,unknown,4
2,35,management,married,tertiary,0,231,1,0,unknown,5,may,139,1,-1,0,unknown,6
3,28,management,single,tertiary,0,447,1,1,unknown,5,may,217,1,-1,0,unknown,7
4,58,technician,married,unknown,0,71,1,0,unknown,5,may,71,1,-1,0,unknown,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13559,68,retired,married,secondary,0,1146,0,0,cellular,16,nov,212,1,187,6,success,45196
13560,36,management,single,secondary,0,1511,1,0,cellular,16,nov,270,1,-1,0,unknown,45198
13561,34,blue-collar,single,secondary,0,1475,1,0,cellular,16,nov,1166,3,530,12,other,45200
13562,53,management,married,tertiary,0,583,0,0,cellular,17,nov,226,1,184,4,success,45202
13563,34,admin.,single,secondary,0,557,0,0,cellular,17,nov,224,1,-1,0,unknown,45203

In [95]:

predict_df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
0,33,entrepreneur,married,secondary,0,2,1,1,unknown,5,may,76,1,-1,0,unknown
1,47,blue-collar,married,unknown,0,1506,1,0,unknown,5,may,92,1,-1,0,unknown
2,35,management,married,tertiary,0,231,1,0,unknown,5,may,139,1,-1,0,unknown
3,28,management,single,tertiary,0,447,1,1,unknown,5,may,217,1,-1,0,unknown
4,58,technician,married,unknown,0,71,1,0,unknown,5,may,71,1,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13559,68,retired,married,secondary,0,1146,0,0,cellular,16,nov,212,1,187,6,success
13560,36,management,single,secondary,0,1511,1,0,cellular,16,nov,270,1,-1,0,unknown
13561,34,blue-collar,single,secondary,0,1475,1,0,cellular,16,nov,1166,3,530,12,other
13562,53,management,married,tertiary,0,583,0,0,cellular,17,nov,226,1,184,4,success
13563,34,admin.,single,secondary,0,557,0,0,cellular,17,nov,224,1,-1,0,unknown

In [96]:
predict_df_1 = pd.get_dummies(predict_df)

In [98]:
predict_df_1.shape

(13564, 48)

In [99]:
future_proba = rf.predict(predict_df_1)

In [103]:
result_file= pd.DataFrame(future_proba)

In [105]:
result_file.to_csv(r'C:\Users\narma\Dropbox\datasets_edvancer_project\bank_problem\Narmathaa_Palanisamy_P5_part_2.csv')

## For objective question

In [106]:
bank_train

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,ID,y
0,45,blue-collar,married,secondary,no,2,no,no,cellular,26,aug,105,10,-1,0,unknown,22944,no
1,34,admin.,divorced,secondary,no,0,no,no,cellular,10,jul,268,1,-1,0,unknown,13870,no
2,40,technician,divorced,secondary,no,311,no,no,cellular,6,aug,738,2,-1,0,unknown,19301,yes
3,58,self-employed,married,tertiary,no,5810,no,no,cellular,12,mar,139,1,-1,0,unknown,31334,yes
4,59,blue-collar,married,secondary,no,169,yes,no,unknown,16,may,181,3,-1,0,unknown,3849,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31642,37,technician,married,secondary,no,6963,yes,no,cellular,22,dec,158,2,-1,0,unknown,42547,no
31643,54,management,married,tertiary,no,8295,no,no,cellular,2,oct,849,2,119,1,success,41684,yes
31644,47,technician,married,tertiary,no,192,yes,no,unknown,26,may,596,1,-1,0,unknown,5827,no
31645,39,admin.,married,secondary,no,0,yes,no,cellular,17,jul,69,1,-1,0,unknown,15012,no
31646,46,blue-collar,married,primary,no,143,yes,no,unknown,7,may,279,1,-1,0,unknown,965,no

In [111]:
bank_train['age'].mean()

40.9146838562897

In [117]:
def detect_outliers_iqr_df(bank_train, columns):
    outliers = {}
    for col in columns:
        q1, q3 = np.percentile(bank_train[col], [25, 75])
        iqr = q3 - q1
        lower_bound = q1 - (1.5 * iqr)
        upper_bound = q3 + (1.5 * iqr)
        outliers[col] = bank_train[(bank_train[col] < lower_bound) | (bank_train[col] > upper_bound)][col]
    return outliers

In [118]:
# Detect outliers in specified columns
columns_to_check = ['balance']  # Specify the columns to check for outliers
outliers = detect_outliers_iqr_df(bank_train, columns_to_check)
print("Outliers:", outliers)

Outliers: {'balance': 3        5810
32       7290
33       6945
36       7180
53       3575
         ...
31604    5341
31627    4943
31628    8883
31642    6963
31643    8295
Name: balance, Length: 3329, dtype: int64}

In [122]:
pd.DataFrame(outliers)

       balance
3         5810
32        7290
33        6945
36        7180
53        3575
...        ...
31604     5341
31627     4943
31628     8883
31642     6963
31643     8295

[3329 rows x 1 columns]

In [124]:
bank_train.describe()

,age,balance,day,duration,campaign,pdays,previous,ID
count,31647.000000,31647.000000,31647.000000,31647.000000,31647.000000,31647.000000,31647.000000,31647.000000
mean,40.914684,1348.265902,15.765791,258.329194,2.757639,40.105381,0.573640,22611.890606
std,10.621688,3045.202189,8.312245,255.658170,3.084175,100.089075,2.419964,13066.970590
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000,1.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000,11276.500000
50%,39.000000,445.000000,16.000000,181.000000,2.000000,-1.000000,0.000000,22625.000000
75%,48.000000,1414.000000,21.000000,320.000000,3.000000,-1.000000,0.000000,33953.500000
max,95.000000,102127.000000,31.000000,3785.000000,58.000000,854.000000,275.000000,45211.000000

In [125]:
bank_train['balance'].var()

9273256.369065026

In [126]:
3045.202189 * 3045.202189

9273256.371890392

In [129]:
bank_train['y'].value_counts(normalize = True)

y
no     0.882453
yes    0.117547
Name: proportion, dtype: float64